import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const html=fs.readFileSync('index.html','utf8');
const script=[...html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)].find(m=>m[2].includes("const CLIENT_ID="))[2];
function setup(){const nodes=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',style:{},querySelector:s=>node(id+s)});return nodes.get(id);};const context={document:{getElementById:node},window:{addEventListener(){}},Chart:{register(){}},ChartDataLabels:{},DOMPurify:{sanitize:x=>x},console,Intl,Date,setTimeout,clearTimeout,localStorage:{},navigator:{},fetch(){throw Error('Unexpected network');}};vm.createContext(context);vm.runInContext(script,context);return {run:s=>vm.runInContext(s,context),node};}
test('fallback de volume não calcula conversão e contém frete',()=>{const c=setup();c.run("G.raw.funnelIsSequential=false;renderFunnel([{eventname:'add_to_cart',eventcount:2},{eventname:'purchase',eventcount:5}])");assert.equal(c.node('funnelCard.ctitle').textContent,'Volume de eventos');assert(!c.node('funnelWrap').innerHTML.includes('conclusão'));assert(c.node('funnelWrap').innerHTML.includes('Shipping'));});
test('funil sequencial diferencia usuários de transações',()=>{const c=setup();c.run("G.raw.funnelIsSequential=true;G.raw.totals={ecommercepurchases:2640};G.raw.eventVolume=[{eventname:'purchase',activeusers:950}];renderFunnel([{funnelstepname:'7. purchase',activeusers:921}])");assert(c.node('funnelWrap').innerHTML.includes('921 usuários completaram'));assert(c.node('funnelWrap').innerHTML.includes('950 usuários dispararam'));assert(c.node('funnelWrap').innerHTML.includes('2.640 transações'));});
test('parser preserva not set e separa dimensões auxiliares',()=>{const c=setup();const rows=c.run("parseRep({dimensionHeaders:[{name:'customEvent:attr_last_source'}],metricHeaders:[{name:'purchaseRevenue'}],rows:[{dimensionValues:[{value:'(not set)'}],metricValues:[{value:'1.2'}]}]})");assert.equal(rows[0].attrlastsource,'(not set)');assert.equal(rows[0].purchaserevenue,1.2);});
test('parser aceita relatório consolidado sem dimensões',()=>{const c=setup();const rows=c.run("parseRep({metricHeaders:[{name:'sessions'},{name:'totalUsers'}],rows:[{metricValues:[{value:'1761'},{value:'1602'}]}]})");assert.equal(rows.length,1);assert.equal(rows[0].sessions,1761);assert.equal(rows[0].totalusers,1602);});
test('funil replica a jornada completa em sete etapas indiretas',()=>{const c=setup();const b=c.run("funnelBody({startDate:'2026-09-01',endDate:'2026-09-11'})");assert.deepEqual(Array.from(b.funnel.steps,s=>s.name),['page_view','view_item','add_to_cart','begin_checkout','add_shipping_info','add_payment_info','purchase']);assert.equal(b.funnel.isOpenFunnel,false);assert(b.funnel.steps.every(s=>s.isDirectlyFollowedBy===false));});
test('período personalizado conta as duas pontas e campanhas codificadas conciliam',()=>{const c=setup();c.node('fPer').value='custom';c.node('fDS').value='2026-09-01';c.node('fDE').value='2026-09-13';assert.equal(c.run('getDias()'),13);assert.equal(c.run("campaignKey('%5BAD5%5D%20%5BCOMPRA%5D','Instagram','paid_social')"),c.run("campaignKey('[AD5] [COMPRA]','instagram','paid_social')"));});
test('chaves inválidas não viram datas no histórico',()=>{const c=setup();assert.equal(c.run("validPeriodKey('(not set)',false)"),false);assert.equal(c.run("validPeriodKey('202609',false)"),true);assert.equal(c.run("validPeriodKey('20260913',true)"),true);});
test('abandono usa os campos oficiais da etapa do funil',()=>{assert.match(script,/funnelstepabandonmentrate/);assert.match(script,/funnelstepabandonments/);assert.doesNotMatch(script,/100\*cart\.abandonmentrate/);});
test('tabelas dinâmicas criam células DOM em vez de sanitizar fragmentos tr',()=>{assert.match(script,/function renderTable[\s\S]*?body\.replaceChildren\(\)/);assert.match(script,/function renderAttrRows[\s\S]*?document\.createElement\('td'\)/);assert.doesNotMatch(script,/attrFirstBody[\s\S]{0,800}innerHTML=safeHtml/);});
