const {chromium}=require('@playwright/test');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const server=http.createServer((req,res)=>{const name=req.url.split('?')[0];if(name==='/'){res.setHeader('Content-Type','text/html');res.end('<style>'+fs.readFileSync('index.html','utf8').split('<style>')[1].split('</style>')[0]+'</style><div class="app"><div id="filterCard"></div></div><script type="module">import {mountGoals} from "/goals-ui.mjs";import {validateGoal} from "/goals-core.mjs";const data={};window.service={load:async(p,m)=>data[p.clientId+m]||null,history:async()=>[],save:async(p,g,v)=>{if((data[p.clientId+g.month]?.version||0)!==v)throw Error("conflito");data[p.clientId+g.month]={...validateGoal(g),version:v+1};},listClients:async()=>[]};mountGoals(window.service);window.ready=true;</script>');}else if(['/goals-ui.mjs','/goals-core.mjs'].includes(name)){res.setHeader('Content-Type','text/javascript');res.end(fs.readFileSync(path.join(process.cwd(),name)));}else{res.statusCode=404;res.end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});
 try {const page=await browser.newPage();const errors=[],requests=[];let failCost=false;page.on('pageerror',e=>errors.push(e.message));await page.route('https://analyticsdata.googleapis.com/**',route=>{const body=route.request().postDataJSON();requests.push(body);const cost=body.metrics[0].name==='advertiserAdCost';if(cost&&failCost)return route.fulfill({status:403,json:{error:{message:'custo negado'}}});return route.fulfill({json:{rows:[{metricValues:(cost?['100']:['500','2']).map(value=>({value}))}]}});});
 await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.ready);
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('dashboard-access',{detail:{isAdmin:true}})));await page.waitForSelector('#adminPanel');assert.equal(await page.locator('#adminPanel').count(),1);
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('dashboard-access',{detail:{isAdmin:false}})));assert.equal(await page.locator('#adminPanel').count(),0);
 const select=async(client,role)=>{await page.evaluate(({client,role})=>window.dispatchEvent(new CustomEvent('dashboard-property',{detail:{property:{id:'123',clientId:client,clientName:client,nome:'Loja',role,currency:'BRL',timeZone:'America/Sao_Paulo',configConfirmed:true,costCoverage:false},token:'TEST'}})),{client,role});await page.waitForFunction(()=>document.querySelector('#goalsPanel [role=status]').textContent.includes('Somente leitura')||document.querySelector('#goalsPanel [role=status]').textContent.includes('Edição autorizada'));};
 await select('a','manager');await page.locator('input[type=number]').first().fill('1000');await page.getByRole('button',{name:'Salvar metas'}).click();await page.waitForFunction(()=>document.querySelector('#goalsPanel [role=status]').textContent.includes('Meta salva'));
 assert.ok(await page.locator('#goalsPanel').innerText().then(t=>t.includes('5.00x')&&!t.includes('cobertura não validada')&&!t.includes('Sem avaliação')));
 await page.locator('input[type=month]').fill('2024-02');await page.getByRole('button',{name:'Recarregar',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#goalsPanel [role=status]').textContent.includes('2024-02-29'));
 assert.ok(requests.some(r=>r.metrics[0].name==='advertiserAdCost'&&r.dimensions[0].name==='sessionSource'&&r.dateRanges[0].startDate==='2024-02-01'&&r.dateRanges[0].endDate==='2024-02-29'));
 failCost=true;await page.getByRole('button',{name:'Recarregar',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#goalsPanel').textContent.includes('custo negado'));
 assert.ok((await page.locator('#goalsPanel tbody').innerText()).includes('500,00'));failCost=false;
 await page.locator('input[type=month]').fill(new Date().toISOString().slice(0,7));await page.getByRole('button',{name:'Recarregar',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#goalsPanel input[type=number]').value==='1000');
 assert.equal(await page.getByRole('button',{name:'Salvar metas'}).isDisabled(),false);
 await select('b','manager');assert.equal(await page.locator('input[type=number]').first().inputValue(),'');
 await select('a','viewer');assert.equal(await page.locator('input[type=number]').first().inputValue(),'1000');assert.equal(await page.getByRole('button',{name:'Salvar metas'}).isDisabled(),true);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/goals-mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'test-results/goals-desktop.png',fullPage:true});
 await page.evaluate(()=>window.dispatchEvent(new Event('dashboard-logout')));assert.equal(await page.locator('#goalsPanel').isVisible(),false);assert.deepEqual(errors,[]);console.log('UI OK: save, tenant isolation, viewer, mobile, logout.');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
